//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomArgentina.PersonalWebService.Proxies.ObtenerSuspHistContrato
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openuri.org/", ConfigurationName = "ObtenerSuspHistContratoSoap")]
    public interface ObtenerSuspHistContratoSoap
    {

        // CODEGEN: Generating message contract since message part namespace (http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0) does not match the default value (http://www.openuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/clientRequestwithReturn", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "ObtenerSuspHistContratoResponseSOAP")]
        clientRequestwithReturnResponse clientRequestwithReturn(clientRequestwithReturnRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://www.openuri.org/clientRequestwithReturn", ReplyAction = "*")]
        System.IAsyncResult BeginclientRequestwithReturn(clientRequestwithReturnRequest request, System.AsyncCallback callback, object asyncState);

        clientRequestwithReturnResponse EndclientRequestwithReturn(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class ObtenerSuspHistContratoRequestSOAP
    {

        private requestHeader requestHeaderField;

        private ObtenerSuspHistContratoRequestSOAPBody bodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0", Order = 0)]
        public requestHeader requestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ObtenerSuspHistContratoRequestSOAPBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeader
    {

        private requestHeaderConsumer consumerField;

        private requestHeaderTransport transportField;

        private requestHeaderMessage messageField;

        private requestHeaderService serviceField;

        private requestHeaderQualityOfService qualityOfServiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public requestHeaderConsumer consumer
        {
            get
            {
                return this.consumerField;
            }
            set
            {
                this.consumerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public requestHeaderTransport transport
        {
            get
            {
                return this.transportField;
            }
            set
            {
                this.transportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public requestHeaderMessage message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public requestHeaderService service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public requestHeaderQualityOfService qualityOfService
        {
            get
            {
                return this.qualityOfServiceField;
            }
            set
            {
                this.qualityOfServiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderConsumer
    {

        private string userIDField;

        private requestHeaderConsumerCredentials credentialsField;

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public requestHeaderConsumerCredentials credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderConsumerCredentials
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userCertificate", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("userPassword", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        userCertificate,

        /// <remarks/>
        userPassword,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderTransport
    {

        private string appIDField;

        private string replyToQueueField;

        private string replyToQueueManagerField;

        private string serviceIDField;

        private string communicationTypeField;

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string appID
        {
            get
            {
                return this.appIDField;
            }
            set
            {
                this.appIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string replyToQueue
        {
            get
            {
                return this.replyToQueueField;
            }
            set
            {
                this.replyToQueueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string replyToQueueManager
        {
            get
            {
                return this.replyToQueueManagerField;
            }
            set
            {
                this.replyToQueueManagerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string serviceID
        {
            get
            {
                return this.serviceIDField;
            }
            set
            {
                this.serviceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string communicationType
        {
            get
            {
                return this.communicationTypeField;
            }
            set
            {
                this.communicationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderMessage
    {

        private string timestampField;

        private string dateField;

        private string expirationField;

        private string messageIdField;

        private string correlationIdField;

        private string conversationIdField;

        private string priorityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        public string expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conversationId
        {
            get
            {
                return this.conversationIdField;
            }
            set
            {
                this.conversationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderService
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderQualityOfService
    {

        private string retryCounterField;

        private string subServiceNameField;

        private string retryTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string retryCounter
        {
            get
            {
                return this.retryCounterField;
            }
            set
            {
                this.retryCounterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string subServiceName
        {
            get
            {
                return this.subServiceNameField;
            }
            set
            {
                this.subServiceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string retryType
        {
            get
            {
                return this.retryTypeField;
            }
            set
            {
                this.retryTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class ObtenerSuspHistContratoRequestSOAPBody
    {

        private ObtenerSuspHistContratoRequestSOAPBodyObtenerSuspHistContrato obtenerSuspHistContratoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ObtenerSuspHistContratoRequestSOAPBodyObtenerSuspHistContrato ObtenerSuspHistContrato
        {
            get
            {
                return this.obtenerSuspHistContratoField;
            }
            set
            {
                this.obtenerSuspHistContratoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class ObtenerSuspHistContratoRequestSOAPBodyObtenerSuspHistContrato
    {

        private string codContratoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/Entities/Cliente/Contrato/v4.0", IsNullable = true, Order = 0)]
        public string codContrato
        {
            get
            {
                return this.codContratoField;
            }
            set
            {
                this.codContratoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class ObtenerSuspHistContratoResponseSOAP
    {

        private responseHeader responseHeaderField;

        private ObtenerSuspHistContratoResponseSOAPBody bodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0", Order = 0)]
        public responseHeader responseHeader
        {
            get
            {
                return this.responseHeaderField;
            }
            set
            {
                this.responseHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ObtenerSuspHistContratoResponseSOAPBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeader
    {

        private responseHeaderConsumer consumerField;

        private responseHeaderMessage messageField;

        private responseHeaderService serviceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public responseHeaderConsumer consumer
        {
            get
            {
                return this.consumerField;
            }
            set
            {
                this.consumerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public responseHeaderMessage message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public responseHeaderService service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeaderConsumer
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeaderMessage
    {

        private string dateField;

        private string expirationField;

        private string statusField;

        private string messageIdField;

        private string correlationIdField;

        private string conversationIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string expiration
        {
            get
            {
                return this.expirationField;
            }
            set
            {
                this.expirationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conversationId
        {
            get
            {
                return this.conversationIdField;
            }
            set
            {
                this.conversationIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeaderService
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class ObtenerSuspHistContratoResponseSOAPBody
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result", typeof(result), Namespace = "http://www.personal.com.ar/Common/ResultMessage/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("ObtenerSuspHistContrato", typeof(ObtenerSuspHistContratoResponseSOAPBodyObtenerSuspHistContrato), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/Common/ResultMessage/v1.0")]
    public partial class result
    {

        private string tipoField;

        private string codigoField;

        private string motivoField;

        private string descripcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class ObtenerSuspHistContratoResponseSOAPBodyObtenerSuspHistContrato
    {

        private Lista_SuspSusp[] lista_SuspField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Susp", IsNullable = false)]
        public Lista_SuspSusp[] Lista_Susp
        {
            get
            {
                return this.lista_SuspField;
            }
            set
            {
                this.lista_SuspField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class Lista_SuspSusp
    {

        private string descripcionSuspensionField;

        private string fechaSuspensionField;

        private Lista_SuspSuspFecha_Rehab fecha_RehabField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/Entities/NegocioComun/InteraccionDelNegocio/v2." +
            "0", ElementName = "fechaSuspension")]
        public string fechaSuspension
        {
            get
            {
                return this.fechaSuspensionField;
            }
            set
            {
                this.fechaSuspensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fecha_Rehab")]
        public Lista_SuspSuspFecha_Rehab Fecha_Rehab
        {
            get
            {
                return this.fecha_RehabField;
            }
            set
            {
                this.fecha_RehabField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/Entities/NegocioComun/InteraccionDelNegocio/v2." +
            "0", ElementName = "descripcionSuspension")]
        public string descripcionSuspension
        {
            get
            {
                return this.descripcionSuspensionField;
            }
            set
            {
                this.descripcionSuspensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
    public partial class Lista_SuspSuspFecha_Rehab
    {

        private string fechaRehabilitacionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/Entities/NegocioComun/InteraccionDelNegocio/v2." +
            "0", Order = 0)]
        public string fechaRehabilitacion
        {
            get
            {
                return this.fechaRehabilitacionField;
            }
            set
            {
                this.fechaRehabilitacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "clientRequestwithReturn", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class clientRequestwithReturnRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
        public ObtenerSuspHistContratoRequestSOAP ObtenerSuspHistContratoRequestSOAP;

        public clientRequestwithReturnRequest()
        {
        }

        public clientRequestwithReturnRequest(ObtenerSuspHistContratoRequestSOAP ObtenerSuspHistContratoRequestSOAP)
        {
            this.ObtenerSuspHistContratoRequestSOAP = ObtenerSuspHistContratoRequestSOAP;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "clientRequestwithReturnResponse", WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class clientRequestwithReturnResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/ESB/ObtenerSuspHistContrato/v1.0")]
        public ObtenerSuspHistContratoResponseSOAP ObtenerSuspHistContratoResponseSOAP;

        public clientRequestwithReturnResponse()
        {
        }

        public clientRequestwithReturnResponse(ObtenerSuspHistContratoResponseSOAP ObtenerSuspHistContratoResponseSOAP)
        {
            this.ObtenerSuspHistContratoResponseSOAP = ObtenerSuspHistContratoResponseSOAP;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObtenerSuspHistContratoSoapChannel : ObtenerSuspHistContratoSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerSuspHistContratoSoapClient : System.ServiceModel.ClientBase<ObtenerSuspHistContratoSoap>, ObtenerSuspHistContratoSoap
    {

        public ObtenerSuspHistContratoSoapClient()
        {
        }

        public ObtenerSuspHistContratoSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ObtenerSuspHistContratoSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ObtenerSuspHistContratoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ObtenerSuspHistContratoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientRequestwithReturnResponse ObtenerSuspHistContratoSoap.clientRequestwithReturn(clientRequestwithReturnRequest request)
        {
            return base.Channel.clientRequestwithReturn(request);
        }

        public ObtenerSuspHistContratoResponseSOAP clientRequestwithReturn(ObtenerSuspHistContratoRequestSOAP ObtenerSuspHistContratoRequestSOAP)
        {
            clientRequestwithReturnRequest inValue = new clientRequestwithReturnRequest();
            inValue.ObtenerSuspHistContratoRequestSOAP = ObtenerSuspHistContratoRequestSOAP;
            clientRequestwithReturnResponse retVal = ((ObtenerSuspHistContratoSoap)(this)).clientRequestwithReturn(inValue);
            return retVal.ObtenerSuspHistContratoResponseSOAP;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ObtenerSuspHistContratoSoap.BeginclientRequestwithReturn(clientRequestwithReturnRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginclientRequestwithReturn(request, callback, asyncState);
        }

        public System.IAsyncResult BeginclientRequestwithReturn(ObtenerSuspHistContratoRequestSOAP ObtenerSuspHistContratoRequestSOAP, System.AsyncCallback callback, object asyncState)
        {
            clientRequestwithReturnRequest inValue = new clientRequestwithReturnRequest();
            inValue.ObtenerSuspHistContratoRequestSOAP = ObtenerSuspHistContratoRequestSOAP;
            return ((ObtenerSuspHistContratoSoap)(this)).BeginclientRequestwithReturn(inValue, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientRequestwithReturnResponse ObtenerSuspHistContratoSoap.EndclientRequestwithReturn(System.IAsyncResult result)
        {
            return base.Channel.EndclientRequestwithReturn(result);
        }

        public ObtenerSuspHistContratoResponseSOAP EndclientRequestwithReturn(System.IAsyncResult result)
        {
            clientRequestwithReturnResponse retVal = ((ObtenerSuspHistContratoSoap)(this)).EndclientRequestwithReturn(result);
            return retVal.ObtenerSuspHistContratoResponseSOAP;
        }
    }
}