//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomArgentina.PersonalWebService.Proxies.ObtenerResumenDeCuenta
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openuri.org/",
        ConfigurationName = "ObtenerResumenDeCuentaSoap")]
    public interface ObtenerResumenDeCuentaSoap
    {

        // CODEGEN: Generating message contract since message part namespace (http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0) does not match the default value (http://www.openuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openuri.org/clientRequestwithReturn",
            ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "ObtenerResumenDeCuentaResponseSOAP")]
        clientRequestwithReturnResponse clientRequestwithReturn(clientRequestwithReturnRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true,
            Action = "http://www.openuri.org/clientRequestwithReturn", ReplyAction = "*")]
        System.IAsyncResult BeginclientRequestwithReturn(clientRequestwithReturnRequest request,
            System.AsyncCallback callback, object asyncState);

        clientRequestwithReturnResponse EndclientRequestwithReturn(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaRequestSOAP
    {

        private requestHeader requestHeaderField;

        private ObtenerResumenDeCuentaRequestSOAPBody bodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0",
[System.Xml.Serialization.XmlElementAttribute("requestHeader")]
        public requestHeader requestHeader
        {
            get { return this.requestHeaderField; }
            set { this.requestHeaderField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("Body")]
        public ObtenerResumenDeCuentaRequestSOAPBody Body
        {
            get { return this.bodyField; }
            set { this.bodyField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeader
    {

        private requestHeaderConsumer consumerField;

        private requestHeaderTransport transportField;

        private requestHeaderMessage messageField;

        private requestHeaderService serviceField;

        private requestHeaderQualityOfService qualityOfServiceField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("consumer")]
        public requestHeaderConsumer consumer
        {
            get { return this.consumerField; }
            set { this.consumerField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("transport")]
        public requestHeaderTransport transport
        {
            get { return this.transportField; }
            set { this.transportField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("message")]
        public requestHeaderMessage message
        {
            get { return this.messageField; }
            set { this.messageField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("service")]
        public requestHeaderService service
        {
            get { return this.serviceField; }
            set { this.serviceField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("qualityOfService")]
        public requestHeaderQualityOfService qualityOfService
        {
            get { return this.qualityOfServiceField; }
            set { this.qualityOfServiceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderConsumer
    {

        private string userIDField;

        private requestHeaderConsumerCredentials credentialsField;

        private string codeField;

        private string nameField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("userID")]
        public string userID
        {
            get { return this.userIDField; }
            set { this.userIDField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("credentials")]
        public requestHeaderConsumerCredentials credentials
        {
            get { return this.credentialsField; }
            set { this.credentialsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderConsumerCredentials
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userCertificate", typeof (string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("userPassword", typeof (string), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0",
        IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        userCertificate,

        /// <remarks/>
        userPassword,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderTransport
    {

        private string appIDField;

        private string replyToQueueField;

        private string replyToQueueManagerField;

        private string serviceIDField;

        private string communicationTypeField;

        private string codeField;

        private string nameField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("appID")]
        public string appID
        {
            get { return this.appIDField; }
            set { this.appIDField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("replyToQueue")]
        public string replyToQueue
        {
            get { return this.replyToQueueField; }
            set { this.replyToQueueField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("replyToQueueManager")]
        public string replyToQueueManager
        {
            get { return this.replyToQueueManagerField; }
            set { this.replyToQueueManagerField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("serviceID")]
        public string serviceID
        {
            get { return this.serviceIDField; }
            set { this.serviceIDField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("communicationType")]
        public string communicationType
        {
            get { return this.communicationTypeField; }
            set { this.communicationTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderMessage
    {

        private string timestampField;

        private string dateField;

        private string expirationField;

        private string messageIdField;

        private string correlationIdField;

        private string conversationIdField;

        private string priorityField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("timestamp")]
        public string timestamp
        {
            get { return this.timestampField; }
            set { this.timestampField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("date")]
        public string date
        {
            get { return this.dateField; }
            set { this.dateField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(DataType = "integer",ElementName = "expiration")]
        public string expiration
        {
            get { return this.expirationField; }
            set { this.expirationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageId
        {
            get { return this.messageIdField; }
            set { this.messageIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string correlationId
        {
            get { return this.correlationIdField; }
            set { this.correlationIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conversationId
        {
            get { return this.conversationIdField; }
            set { this.conversationIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string priority
        {
            get { return this.priorityField; }
            set { this.priorityField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderService
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderRequest/v1.0")]
    public partial class requestHeaderQualityOfService
    {

        private string retryCounterField;

        private string subServiceNameField;

        private string retryTypeField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(DataType = "integer",ElementName = "retryCounter")]
        public string retryCounter
        {
            get { return this.retryCounterField; }
            set { this.retryCounterField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("subServiceName")]
        public string subServiceName
        {
            get { return this.subServiceNameField; }
            set { this.subServiceNameField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("retryType")]
        public string retryType
        {
            get { return this.retryTypeField; }
            set { this.retryTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaRequestSOAPBody
    {

        private ObtenerResumenDeCuentaRequestSOAPBodyObtenerResumenDeCuenta obtenerResumenDeCuentaField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("ObtenerResumenDeCuenta")]
        public ObtenerResumenDeCuentaRequestSOAPBodyObtenerResumenDeCuenta ObtenerResumenDeCuenta
        {
            get { return this.obtenerResumenDeCuentaField; }
            set { this.obtenerResumenDeCuentaField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaRequestSOAPBodyObtenerResumenDeCuenta
    {

        private string codCuentaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(
Namespace = "http://www.personal.com.ar/Common/Entities/Cliente/Cuenta/v1.0", IsNullable = true,ElementName = "codCuenta")]
        public string codCuenta
        {
            get { return this.codCuentaField; }
            set { this.codCuentaField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaResponseSOAP
    {

        private responseHeader responseHeaderField;

        private ObtenerResumenDeCuentaResponseSOAPBody bodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(
Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0",ElementName = "responseHeader")]
        public responseHeader responseHeader
        {
            get { return this.responseHeaderField; }
            set { this.responseHeaderField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("Body")]
        public ObtenerResumenDeCuentaResponseSOAPBody Body
        {
            get { return this.bodyField; }
            set { this.bodyField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeader
    {

        private responseHeaderConsumer consumerField;

        private responseHeaderMessage messageField;

        private responseHeaderService serviceField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("consumer")]
        public responseHeaderConsumer consumer
        {
            get { return this.consumerField; }
            set { this.consumerField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("message")]
        public responseHeaderMessage message
        {
            get { return this.messageField; }
            set { this.messageField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("service")]
        public responseHeaderService service
        {
            get { return this.serviceField; }
            set { this.serviceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeaderConsumer
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeaderMessage
    {

        private string dateField;

        private string expirationField;

        private string statusField;

        private string messageIdField;

        private string correlationIdField;

        private string conversationIdField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("date")]
        public string date
        {
            get { return this.dateField; }
            set { this.dateField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(DataType = "integer",ElementName = "expiration")]
        public string expiration
        {
            get { return this.expirationField; }
            set { this.expirationField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("status")]
        public string status
        {
            get { return this.statusField; }
            set { this.statusField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageId
        {
            get { return this.messageIdField; }
            set { this.messageIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string correlationId
        {
            get { return this.correlationIdField; }
            set { this.correlationIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conversationId
        {
            get { return this.conversationIdField; }
            set { this.conversationIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/HeaderResponse/v1.0")]
    public partial class responseHeaderService
    {

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaResponseSOAPBody
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result", typeof (result),
            Namespace = "http://www.personal.com.ar/Common/ResultMessage/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("ObtenerResumenDeCuenta",
typeof (ObtenerResumenDeCuentaResponseSOAPBodyObtenerResumenDeCuenta),ElementName = "Item")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/Common/ResultMessage/v1.0")]
    public partial class result
    {

        private string tipoField;

        private string codigoField;

        private string motivoField;

        private string descripcionField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified,ElementName = "tipo")]
        public string tipo
        {
            get { return this.tipoField; }
            set { this.tipoField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified,ElementName = "codigo")]
        public string codigo
        {
            get { return this.codigoField; }
            set { this.codigoField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified,ElementName = "motivo")]
        public string motivo
        {
            get { return this.motivoField; }
            set { this.motivoField = value; }
        }

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified,ElementName = "descripcion")]
        public string descripcion
        {
            get { return this.descripcionField; }
            set { this.descripcionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaResponseSOAPBodyObtenerResumenDeCuenta
    {

        private ObtenerResumenDeCuentaResponseSOAPBodyObtenerResumenDeCuentaLista[] listaField;

        /// <remarks/>
[System.Xml.Serialization.XmlElementAttribute("Lista",ElementName = "Lista")]
        public ObtenerResumenDeCuentaResponseSOAPBodyObtenerResumenDeCuentaLista[] Lista
        {
            get { return this.listaField; }
            set { this.listaField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]
    public partial class ObtenerResumenDeCuentaResponseSOAPBodyObtenerResumenDeCuentaLista
    {

        private string importeComprobanteField;

        private string fechaEmisionComprobanteField;

        private string importeComprobanteImpagoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(
            Namespace = "http://www.personal.com.ar/Common/Entities/Cliente/Comprobante/v2.0", ElementName = "importeComprobante")]
        public string importeComprobante
        {
            get { return this.importeComprobanteField; }
            set { this.importeComprobanteField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(
            Namespace = "http://www.personal.com.ar/Common/Entities/Cliente/Comprobante/v2.0", ElementName = "fechaEmisionComprobante")]
        public string fechaEmisionComprobante
        {
            get { return this.fechaEmisionComprobanteField; }
            set { this.fechaEmisionComprobanteField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(
            Namespace = "http://www.personal.com.ar/Common/Entities/Cliente/Comprobante/v2.0", ElementName = "importeComprobanteImpago")]
        public string importeComprobanteImpago
        {
            get { return this.importeComprobanteImpagoField; }
            set { this.importeComprobanteImpagoField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "clientRequestwithReturn",
        WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class clientRequestwithReturnRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(
Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0",ElementName = ""http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]")]
                Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")] public
            ObtenerResumenDeCuentaRequestSOAP ObtenerResumenDeCuentaRequestSOAP;

        public clientRequestwithReturnRequest()
        {
        }

        public clientRequestwithReturnRequest(ObtenerResumenDeCuentaRequestSOAP ObtenerResumenDeCuentaRequestSOAP)
        {
            this.ObtenerResumenDeCuentaRequestSOAP = ObtenerResumenDeCuentaRequestSOAP;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "clientRequestwithReturnResponse",
        WrapperNamespace = "http://www.openuri.org/", IsWrapped = true)]
    public partial class clientRequestwithReturnResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(
Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0",ElementName = ""http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")]")]
                Namespace = "http://www.personal.com.ar/ESB/ObtenerResumenDeCuenta/v1.0")] public
            ObtenerResumenDeCuentaResponseSOAP ObtenerResumenDeCuentaResponseSOAP;

        public clientRequestwithReturnResponse()
        {
        }

        public clientRequestwithReturnResponse(ObtenerResumenDeCuentaResponseSOAP ObtenerResumenDeCuentaResponseSOAP)
        {
            this.ObtenerResumenDeCuentaResponseSOAP = ObtenerResumenDeCuentaResponseSOAP;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObtenerResumenDeCuentaSoapChannel : ObtenerResumenDeCuentaSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerResumenDeCuentaSoapClient : System.ServiceModel.ClientBase<ObtenerResumenDeCuentaSoap>,
        ObtenerResumenDeCuentaSoap
    {

        public ObtenerResumenDeCuentaSoapClient()
        {
        }

        public ObtenerResumenDeCuentaSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ObtenerResumenDeCuentaSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ObtenerResumenDeCuentaSoapClient(string endpointConfigurationName,
            System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ObtenerResumenDeCuentaSoapClient(System.ServiceModel.Channels.Binding binding,
            System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientRequestwithReturnResponse ObtenerResumenDeCuentaSoap.clientRequestwithReturn(
            clientRequestwithReturnRequest request)
        {
            return base.Channel.clientRequestwithReturn(request);
        }

        public ObtenerResumenDeCuentaResponseSOAP clientRequestwithReturn(
            ObtenerResumenDeCuentaRequestSOAP ObtenerResumenDeCuentaRequestSOAP)
        {
            clientRequestwithReturnRequest inValue = new clientRequestwithReturnRequest();
            inValue.ObtenerResumenDeCuentaRequestSOAP = ObtenerResumenDeCuentaRequestSOAP;
            clientRequestwithReturnResponse retVal =
                ((ObtenerResumenDeCuentaSoap) (this)).clientRequestwithReturn(inValue);
            return retVal.ObtenerResumenDeCuentaResponseSOAP;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ObtenerResumenDeCuentaSoap.BeginclientRequestwithReturn(
            clientRequestwithReturnRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginclientRequestwithReturn(request, callback, asyncState);
        }

        public System.IAsyncResult BeginclientRequestwithReturn(
            ObtenerResumenDeCuentaRequestSOAP ObtenerResumenDeCuentaRequestSOAP, System.AsyncCallback callback,
            object asyncState)
        {
            clientRequestwithReturnRequest inValue = new clientRequestwithReturnRequest();
            inValue.ObtenerResumenDeCuentaRequestSOAP = ObtenerResumenDeCuentaRequestSOAP;
            return ((ObtenerResumenDeCuentaSoap) (this)).BeginclientRequestwithReturn(inValue, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientRequestwithReturnResponse ObtenerResumenDeCuentaSoap.EndclientRequestwithReturn(System.IAsyncResult result)
        {
            return base.Channel.EndclientRequestwithReturn(result);
        }

        public ObtenerResumenDeCuentaResponseSOAP EndclientRequestwithReturn(System.IAsyncResult result)
        {
            clientRequestwithReturnResponse retVal =
                ((ObtenerResumenDeCuentaSoap) (this)).EndclientRequestwithReturn(result);
            return retVal.ObtenerResumenDeCuentaResponseSOAP;
        }
    }
}
